version: "3.7"
services:
  postgres_alice:
    image: postgres
    restart: always
    container_name: "postgres_alice"
    environment:
      - POSTGRES_USER=alice
      - POSTGRES_PASSWORD=alice_pass
      - POSTGRES_DB=alice
      - PGDATA=/tmp
    ports:
      - 5433:5432
    volumes:
      - ${STOR}/storage/db_init/:/docker-entrypoint-initdb.d/
      - ${STOR}/storage/pg_data/:/tmp

  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Moscow
    ports:
      - 1888:1880
    volumes:
      - ${STOR}/storage/node-red-data:/data

  mosquitto_alice:
    image: eclipse-mosquitto:1.6.13
    ports:
      - 11883:1883
    # volumes:
    #   - ${WD}/storage/mosquitto-data:/mosquitto

    # volumes:
    #   tmp:
    #     external: false
    #     name: tmp
