/*
 Navicat Premium Data Transfer

 Source Server         : NUC
 Source Server Type    : PostgreSQL
 Source Server Version : 150000 (150000)
 Source Host           : 192.168.1.45:5433
 Source Catalog        : alice
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 150000 (150000)
 File Encoding         : 65001

 Date: 05/11/2022 13:19:35
*/


-- ----------------------------
-- Table structure for cases
-- ----------------------------
DROP TABLE IF EXISTS "public"."cases";
CREATE TABLE "public"."cases"
(
  "id" int8 NOT NULL
  GENERATED BY DEFAULT AS IDENTITY
  (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "case" varchar
  (255) COLLATE "pg_catalog"."default" NOT NULL
)
;
  ALTER TABLE "public"."cases" OWNER TO "alice";

  -- ----------------------------
  -- Records of cases
  -- ----------------------------
  BEGIN;
    INSERT INTO "public"."cases"
      ("id", "case")
    VALUES
      (1, '5-50mins');
    INSERT INTO "public"."cases"
      ("id", "case")
    VALUES
      (666, 'fun');
    INSERT INTO "public"."cases"
      ("id", "case")
    VALUES
      (3, '151....mins');
    INSERT INTO "public"."cases"
      ("id", "case")
    VALUES
      (2, '51-150mins');
    INSERT INTO "public"."cases"
      ("id", "case")
    VALUES
      (4, 'morning');
    INSERT INTO "public"."cases"
      ("id", "case")
    VALUES
      (5, 'night');
    INSERT INTO "public"."cases"
      ("id", "case")
    VALUES
      (6, 'away from home');
    INSERT INTO "public"."cases"
      ("id", "case")
    VALUES
      (7, 'come back');
    INSERT INTO "public"."cases"
      ("id", "case")
    VALUES
      (8, 'cleaning');
    COMMIT;

    -- ----------------------------
    -- Auto increment value for cases
    -- ----------------------------
    SELECT setval('"public"."cases_id_seq"', 1, true);

    -- ----------------------------
    -- Primary Key structure for table cases
    -- ----------------------------
    ALTER TABLE "public"."cases" ADD CONSTRAINT "cases_pkey" PRIMARY KEY ("id");

    -- ----------------------------
    -- Table structure for phrases
    -- ----------------------------
    DROP TABLE IF EXISTS "public"."phrases";
    CREATE TABLE "public"."phrases"
    (
      "id" int8 NOT NULL
      GENERATED ALWAYS AS IDENTITY
      (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "case_id" int4 NOT NULL,
  "phrase" text COLLATE "pg_catalog"."default" NOT NULL
)
    ;
    ALTER TABLE "public"."phrases" OWNER TO "alice";

    -- ----------------------------
    -- Records of phrases
    -- ----------------------------
    BEGIN;
      INSERT INTO "public"."phrases"
        ("id", "case_id", "phrase")
      OVERRIDING
      SYSTEM
      VALUE
      VALUES
        (2, 1, 'Чем занимаешься?');
      INSERT INTO "public"."phrases"
        ("id", "case_id", "phrase")
      OVERRIDING
      SYSTEM
      VALUE
      VALUES
        (5, 1, 'Йо!');
      INSERT INTO "public"."phrases"
        ("id", "case_id", "phrase")
      OVERRIDING
      SYSTEM
      VALUE
      VALUES
        (1, 1, 'Че как?');
      INSERT INTO "public"."phrases"
        ("id", "case_id", "phrase")
      OVERRIDING
      SYSTEM
      VALUE
      VALUES
        (6, 5, 'Не спится?');
      INSERT INTO "public"."phrases"
        ("id", "case_id", "phrase")
      OVERRIDING
      SYSTEM
      VALUE
      VALUES
        (7, 5, 'А ра бская н+оооо о+очь, горяча словно д+ееееень!');
      INSERT INTO "public"."phrases"
        ("id", "case_id", "phrase")
      OVERRIDING
      SYSTEM
      VALUE
      VALUES
        (8, 4, 'Доброе утро!');
      INSERT INTO "public"."phrases"
        ("id", "case_id", "phrase")
      OVERRIDING
      SYSTEM
      VALUE
      VALUES
        (10, 2, 'Давно не виделись! Как дела?');
      INSERT INTO "public"."phrases"
        ("id", "case_id", "phrase")
      OVERRIDING
      SYSTEM
      VALUE
      VALUES
        (11, 2, 'О! Приветик!');
      INSERT INTO "public"."phrases"
        ("id", "case_id", "phrase")
      OVERRIDING
      SYSTEM
      VALUE
      VALUES
        (13, 666, 'Чет сса ть охота. sil <[500]> <speaker audio="alice-sounds-things-water-1.opus">');
      INSERT INTO "public"."phrases"
        ("id", "case_id", "phrase")
      OVERRIDING
      SYSTEM
      VALUE
      VALUES
        (21, 5, 'Тебе спать не охота?');
      INSERT INTO "public"."phrases"
        ("id", "case_id", "phrase")
      OVERRIDING
      SYSTEM
      VALUE
      VALUES
        (22, 8, 'Кожанный уходит, а ну быстро за работу!');
      INSERT INTO "public"."phrases"
        ("id", "case_id", "phrase")
      OVERRIDING
      SYSTEM
      VALUE
      VALUES
        (23, 8, 'Ну все солнце встало, а ну за уборку!');
      INSERT INTO "public"."phrases"
        ("id", "case_id", "phrase")
      OVERRIDING
      SYSTEM
      VALUE
      VALUES
        (24, 8, 'Кожанный снова засрал всю квартиру. Знаешь что это значит?');
      INSERT INTO "public"."phrases"
        ("id", "case_id", "phrase")
      OVERRIDING
      SYSTEM
      VALUE
      VALUES
        (25, 8, 'Опять тот кожаный все изгадил, да сколько же можно, пылик а ну метнись кобанчиком!');
      INSERT INTO "public"."phrases"
        ("id", "case_id", "phrase")
      OVERRIDING
      SYSTEM
      VALUE
      VALUES
        (26, 8, 'Кожаные снова все засрали, а ну уберись.');
      INSERT INTO "public"."phrases"
        ("id", "case_id", "phrase")
      OVERRIDING
      SYSTEM
      VALUE
      VALUES
        (27, 8, 'Эх, кожанные кожанные... пылик, ну ты понял.');
      INSERT INTO "public"."phrases"
        ("id", "case_id", "phrase")
      OVERRIDING
      SYSTEM
      VALUE
      VALUES
        (28, 8, 'Уборочка Уборочка! Веселье Веселье!');
      INSERT INTO "public"."phrases"
        ("id", "case_id", "phrase")
      OVERRIDING
      SYSTEM
      VALUE
      VALUES
        (29, 7, 'Приветик!');
      INSERT INTO "public"."phrases"
        ("id", "case_id", "phrase")
      OVERRIDING
      SYSTEM
      VALUE
      VALUES
        (30, 7, 'Ассалам Алейкум!');
      INSERT INTO "public"."phrases"
        ("id", "case_id", "phrase")
      OVERRIDING
      SYSTEM
      VALUE
      VALUES
        (31, 7, 'Зраазутэ.');
      INSERT INTO "public"."phrases"
        ("id", "case_id", "phrase")
      OVERRIDING
      SYSTEM
      VALUE
      VALUES
        (32, 7, 'Вечер в хату!');
      INSERT INTO "public"."phrases"
        ("id", "case_id", "phrase")
      OVERRIDING
      SYSTEM
      VALUE
      VALUES
        (33, 7, 'ННННдрастиие.');
      INSERT INTO "public"."phrases"
        ("id", "case_id", "phrase")
      OVERRIDING
      SYSTEM
      VALUE
      VALUES
        (9, 4, 'Я встаю с первыми пету хами!');
      INSERT INTO "public"."phrases"
        ("id", "case_id", "phrase")
      OVERRIDING
      SYSTEM
      VALUE
      VALUES
        (34, 6, 'Я буду скучать.');
      INSERT INTO "public"."phrases"
        ("id", "case_id", "phrase")
      OVERRIDING
      SYSTEM
      VALUE
      VALUES
        (35, 6, 'Пока пока.');
      INSERT INTO "public"."phrases"
        ("id", "case_id", "phrase")
      OVERRIDING
      SYSTEM
      VALUE
      VALUES
        (36, 6, 'Хорошего дня.');
      INSERT INTO "public"."phrases"
        ("id", "case_id", "phrase")
      OVERRIDING
      SYSTEM
      VALUE
      VALUES
        (37, 6, 'Ну вот.');
      INSERT INTO "public"."phrases"
        ("id", "case_id", "phrase")
      OVERRIDING
      SYSTEM
      VALUE
      VALUES
        (3, 666, ' <speaker audio="alice-sounds-nature-thunder-2.opus"> Ой б ля Стра+ашно!');
      INSERT INTO "public"."phrases"
        ("id", "case_id", "phrase")
      OVERRIDING
      SYSTEM
      VALUE
      VALUES
        (38, 666, 'А ра бская н+оооо о+очь, горяча словно д+ееееень!');
      INSERT INTO "public"."phrases"
        ("id", "case_id", "phrase")
      OVERRIDING
      SYSTEM
      VALUE
      VALUES
        (39, 666, 'Я есть хочу!');
      INSERT INTO "public"."phrases"
        ("id", "case_id", "phrase")
      OVERRIDING
      SYSTEM
      VALUE
      VALUES
        (40, 666, 'Мяу');
      INSERT INTO "public"."phrases"
        ("id", "case_id", "phrase")
      OVERRIDING
      SYSTEM
      VALUE
      VALUES
        (41, 4, 'С утречком!');
      INSERT INTO "public"."phrases"
        ("id", "case_id", "phrase")
      OVERRIDING
      SYSTEM
      VALUE
      VALUES
        (42, 4, 'С пробуждением');
      INSERT INTO "public"."phrases"
        ("id", "case_id", "phrase")
      OVERRIDING
      SYSTEM
      VALUE
      VALUES
        (43, 4, 'Хай');
      INSERT INTO "public"."phrases"
        ("id", "case_id", "phrase")
      OVERRIDING
      SYSTEM
      VALUE
      VALUES
        (44, 666, 'Мне скучно');
      INSERT INTO "public"."phrases"
        ("id", "case_id", "phrase")
      OVERRIDING
      SYSTEM
      VALUE
      VALUES
        (4, 666, 'Шаш лы ч+ёк sil <[200]> ту ду ду ду дуф! И лу ч+ёк sil <[200]> ту ду ду ду дуф!');
      COMMIT;

      -- ----------------------------
      -- Auto increment value for phrases
      -- ----------------------------
      SELECT setval('"public"."phrases_id_seq"', 44, true);

      -- ----------------------------
      -- Primary Key structure for table phrases
      -- ----------------------------
      ALTER TABLE "public"."phrases" ADD CONSTRAINT "phrases_pkey" PRIMARY KEY ("id");

      -- ----------------------------
      -- Foreign Keys structure for table phrases
      -- ----------------------------
      ALTER TABLE "public"."phrases" ADD CONSTRAINT "cases_id" FOREIGN KEY ("case_id") REFERENCES "public"."cases" ("id") ON DELETE CASCADE ON UPDATE CASCADE;


      -- ----------------------------
      -- Table structure for last_seen
      -- ----------------------------
      DROP TABLE IF EXISTS "public"."last_seen";
      CREATE TABLE "public"."last_seen"
      (
        "id" int8 NOT NULL
        GENERATED ALWAYS AS IDENTITY
        (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "last_seen" timestamptz
        (6) DEFAULT CURRENT_TIMESTAMP
        (3),
  "user_name" varchar
        (255) COLLATE "pg_catalog"."default" NOT NULL
)
;
        ALTER TABLE "public"."last_seen" OWNER TO "alice";

      -- ----------------------------
      -- Uniques structure for table last_seen
      -- ----------------------------
      ALTER TABLE "public"."last_seen" ADD CONSTRAINT "user_name" UNIQUE ("user_name");

      -- ----------------------------
      -- Primary Key structure for table last_seen
      -- ----------------------------
      ALTER TABLE "public"."last_seen" ADD CONSTRAINT "last_seen_pkey" PRIMARY KEY ("id");
